name: Docs

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.9.0
      - run: cd docs && pnpm i && pnpm build && echo .vitepress/dist/api/all_match.html